# Generated by Django 2.0.7 on 2018-07-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atracao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atracao',
        ),
    ]
