# Generated by Django 2.0.4 on 2018-08-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
